package com.zheng.hz.model.auto;

public class Person {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column person.id
     *
     * @mbggenerated Sat Nov 26 22:50:44 CST 2016
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column person.name
     *
     * @mbggenerated Sat Nov 26 22:50:44 CST 2016
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column person.iphone
     *
     * @mbggenerated Sat Nov 26 22:50:44 CST 2016
     */
    private String iphone;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column person.id
     *
     * @return the value of person.id
     *
     * @mbggenerated Sat Nov 26 22:50:44 CST 2016
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column person.id
     *
     * @param id the value for person.id
     *
     * @mbggenerated Sat Nov 26 22:50:44 CST 2016
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column person.name
     *
     * @return the value of person.name
     *
     * @mbggenerated Sat Nov 26 22:50:44 CST 2016
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column person.name
     *
     * @param name the value for person.name
     *
     * @mbggenerated Sat Nov 26 22:50:44 CST 2016
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column person.iphone
     *
     * @return the value of person.iphone
     *
     * @mbggenerated Sat Nov 26 22:50:44 CST 2016
     */
    public String getIphone() {
        return iphone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column person.iphone
     *
     * @param iphone the value for person.iphone
     *
     * @mbggenerated Sat Nov 26 22:50:44 CST 2016
     */
    public void setIphone(String iphone) {
        this.iphone = iphone == null ? null : iphone.trim();
    }
}